---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data

```{r loaddata}
data <- read.table("activity.csv", header = TRUE, sep = ",", na.strings = "NA", colClasses = c(date = "Date"))
s <- aggregate(data$steps ~ data$date, FUN = sum, na.rm = TRUE, data = data)
```

## What is mean total number of steps taken per day?

```{r firstHist}
hist(x = s[,2], breaks = 20, col = "purple", xlab = "Daily Total Steps", ylab = "Frequency")
```

## What is the average daily activity pattern?

```{r meanmedian}
mean(s[,2])
median(s[,2])
```

## Imputing missing values

```{r}
data_impute <- data
missing <- is.na(data$steps)
data_impute$steps[missing] <- average[,2][missing]
```

## Are there differences in activity patterns between weekdays and weekends?

```{r weekend}
data_impute$day <- weekdays(data_impute$date)
data_impute$day <- ifelse(data_impute$day == "Sunday" | data_impute$day == "Saturday", "Weekend", "Weekday")
data_impute$day <- as.factor(data_impute$day)
s_impute2 <- aggregate(steps ~ day + interval, FUN = mean, data = data_impute)
library(lattice)
xyplot(steps ~ interval | factor(day), layout = c(1,2), xlab = "Interval", 
         ylab = "Steps", type = "l", data = s_impute2)
```
